# Generated by Django 6.0 on 2026-01-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectshifttemplate_projectplannedday_and_more'),
        ('worklogs', '0008_add_breaks_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='shift_assignment',
            field=models.ForeignKey(blank=True, help_text='Link to the planned shift this worklog fulfills', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='projects.shiftassignment', verbose_name='Shift Assignment'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revised', 'Needs Revision')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
