# Generated by Django 6.0 on 2026-01-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0014_remove_unique_employee_date_shift_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry',
            name='allowances',
            field=models.JSONField(blank=True, default=list, help_text='Array of allowances [{allowance_type: id, hours: float, start_time: HH:MM, end_time: HH:MM}, ...]', verbose_name='Allowances'),
        ),
    ]
