# Generated by Django 6.0 on 2026-06-06

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_default_admin(apps, schema_editor):
    User = apps.get_model('employees', 'User')
    email = 'Infoprototaal@gmail.com'
    
    # Check if the user already exists to avoid duplicates
    if not User.objects.filter(email=email).exists():
        User.objects.create(
            email=email,
            password=make_password('ProTotaalAdmin2026!'),
            is_staff=True,
            is_superuser=True,
            role='admin',
            is_active=True,
            is_first_login=True
        )

def remove_default_admin(apps, schema_editor):
    User = apps.get_model('employees', 'User')
    email = 'Infoprototaal@gmail.com'
    User.objects.filter(email=email).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_add_overtime_threshold'),
    ]

    operations = [
        migrations.RunPython(create_default_admin, reverse_code=remove_default_admin),
    ]
