# Generated by Django 6.0 on 2026-01-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_add_manager_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='house_number',
            field=models.CharField(blank=True, default='', help_text='House/building number (e.g., 123)', max_length=10, verbose_name='House Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='house_number_addition',
            field=models.CharField(blank=True, default='', help_text='Addition to house number (e.g., A, B, bis)', max_length=10, verbose_name='House Number Addition'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street_name',
            field=models.CharField(blank=True, default='', help_text='Name of the street (e.g., Kerkstraat)', max_length=200, verbose_name='Street Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Legacy field - use street_name, house_number, house_number_addition instead', max_length=255, verbose_name='Street Address'),
        ),
    ]
