# Generated by Django 6.0 on 2026-01-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_add_address_fields_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Company website URL', verbose_name='Website'),
        ),
    ]
