# Generated by Django 6.0 on 2026-04-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_add_website_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerallowancesurcharge',
            name='day_percentages',
            field=models.JSONField(blank=True, default=dict, help_text='Per-day-of-week percentage overrides, e.g. {"0": 50, "1": 30, ..., "6": 50, "holiday": 150}. Keys: 0=Mon..6=Sun, "holiday"=holidays.', verbose_name='Per-Day Percentages'),
        ),
        migrations.AddField(
            model_name='customerservicesurcharge',
            name='day_percentages',
            field=models.JSONField(blank=True, default=dict, help_text='Per-day-of-week percentage overrides, e.g. {"0": 50, "1": 30, ..., "6": 50, "holiday": 150}. Keys: 0=Mon..6=Sun, "holiday"=holidays.', verbose_name='Per-Day Percentages'),
        ),
        migrations.AddField(
            model_name='customersurcharge',
            name='day_percentages',
            field=models.JSONField(blank=True, default=dict, help_text='Per-day-of-week percentage overrides, e.g. {"0": 50, "1": 30, ..., "6": 50, "holiday": 150}. Keys: 0=Mon..6=Sun, "holiday"=holidays.', verbose_name='Per-Day Percentages'),
        ),
    ]
