# Generated by Django 6.0 on 2026-04-18 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_add_day_percentages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerallowancesurcharge',
            name='day_percentages',
        ),
        migrations.RemoveField(
            model_name='customerservicesurcharge',
            name='day_percentages',
        ),
        migrations.RemoveField(
            model_name='customersurcharge',
            name='day_percentages',
        ),
    ]
